FROM openjdk:11

ADD ./target/jobrecruiterprofile-service-0.0.1-SNAPSHOT.jar /usr/src/jobrecruiterprofile-service-0.0.1-SNAPSHOT.jar

WORKDIR usr/src


ENTRYPOINT ["java","-jar", "jobrecruiterprofile-service-0.0.1-SNAPSHOT.jar"]
