
#server.name: kibana
#server.host: "0"
#elasticsearch.url: http://localhost:9200
#elasticsearch.username: elastic
#elasticsearch.password: password
#xpack.monitoring.ui.container.elasticsearch.enabled: true
#xpack.security.enabled: false


---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: password
## Session timeout and session duraton
xpack.security.session.idleTimeout: "1h"
xpack.security.session.lifespan: "4h"
## Setting default dashboard
kibana.defaultAppId: "dashboards"